name: lando-docs
services:
  node:
    type: node:18
    build:
      - npm install
    scanner: false
    ssl: false
    sslExpose: false
    overrides:
      ports:
        - 8011:8011
tooling:
  node:
    service: node
  npm:
    service: node

