name: Bump Version

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-24.04
        node-version:
          - '18'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile
      - name: Lint code
        run: npm run lint
      - name: Prepare release
        uses: lando/prepare-release-action@v3
        with:
          sync-token: ${{ secrets.RTFM47_COAXIUM_INJECTOR }}
          sync-email: rtfm47@lando.dev
          sync-username: rtfm-47
